### PR TITLE
Send notifications for mentions

### PR DESCRIPTION
**Pull request by hstove**
Adds logic to check for new mentions and send notifications, if the user has subscribed to them.

### CODE REVIEW

**Comment by hstove** [comment]
@jeffdomke @aulneau this is ready for testing!

Use https://staging.banter.pub . As you can see, there is already some great conversation going on.

Hit 'settings' in the top right, enter your email, make sure you check "notify me when I'm mentioned", and then save. You can then get (very simple, not formatted) emails with a direct link to the message in your email.

**Comment by jeffdomke** [comment]
Some feedback:
• Didn't get an email when I mentioned myself, assume this is desired behavior? 
• The save button in the email settings didn't seem to provide any feedback. Not sure if it saved or not? 
• These social settings should be enabled by default.

**Comment by aulneau** [comment]
@jeffdomke 
screen shot 2019-02-22 at 10 33 46 am

**Comment by aulneau** [comment]
I haven't spent time in the settings page but I can soon, I'll do some fixes and then report back

**Comment by jeffdomke** [comment]
I have two users here both @mentioning each other and no emails are firing?

**Comment by hstove** [comment]
> The save button in the email settings didn't seem to provide any feedback. Not sure if it saved or not?

The little progress bar at the top of the page triggers, but the save is fast so you hardly see it. Should be a notice or something. I've noticed it too.

> Didn't get an email when I mentioned myself, assume this is desired behavior?

Correct, intentional.

> I have two users here both @mentioning each other and no emails are firing?

It seems like it takes a minute or two for Sendgrid to process and send the email. Check now? Sendgrid says they sent the email.

**Comment by jeffdomke** [comment]
Strike that I got them with a decent delay. Anything special happening there or is it just a sever thing?

**Comment by hstove** [comment]
> Anything special happening there or is it just a sever thing?

Nothing special, I can see the activity in Sendgrid as soon as you post the message, but Sendgrid for whatever reason has it in 'processing' for about a minute before its 'delivered'.

**Pull request merged**
