### PR TITLE
Initial profile screen

### PR DESCRIPTION
**Pull request by aulneau**
### What this does

This adds basic functionality for a profile screen and linkable usernames

### CODE REVIEW

**Comment by hstove** [comment]
@jeffdomke want to give this a quick QA to see if you have suggestions?

https://banter-radiks-pr-17.herokuapp.com/

**Comment by jeffdomke** [comment]
Looking pretty good. Is that `hankstoever` displayed the profile first/last? 

I guess I would assume this would show blockstack ID then first last if populated?

**Comment by hstove** [comment]
Nah, Thomas set it to the first part of your blockstack ID. So `hankstoever.id` = `hankstoever`. `hank.blockstack.id` = `hank`. Change it? We can also show both the full name (if available) and the ID

**Comment by jeffdomke** [comment]
Think it seems a bit confusing as is.

**Comment by hstove** [comment]
Added your full name if available, full ID, and links to some social if available.

preview

**Pull request merged**
