### PR TITLE
UI improvements and Redux

### PR DESCRIPTION
**Pull request by aulneau**
### What this does

This just is a collection of a few small fixes: better focus state, loading states for buttons and fixes a bug when loading new messages but you hit the end of the line.

### CODE REVIEW

**Comment by hstove** [comment]
@jeffdomke you should check this out, there are some pretty cool changes.

@aulneau , looks awesome! The only thing I caught is that the profile page is a little off on mobile. Just needs some margin tweaks.

**Comment by jeffdomke** [comment]
Looking pretty fresh. When I click on my avatar I get `An unexpected error has occurred.`

**Comment by hstove** [comment]
@aulneau two fixes to make before merging:

- Hide settings/avatar if logged out
- Add some way to log out if you're logged in

**Comment by aulneau** [comment]
@hstove should be good to go! just need to resolve some conflicts

**Comment by aulneau** [comment]
ok @hstove good to goooooo

**Pull request merged**
